---
version: '3'

services:
  dao-vp-counter:
    container_name: dao-vp-counter
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3111:3000
    # volumes:
      # - ./vp-counter-data.json.json:/app/vp-counter-data.json
